/// Flutter icons OpArtLab
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  OpArtLab
///      fonts:
///       - asset: fonts/OpArtLab.ttf
///
///
///
import 'package:flutter/widgets.dart';

class OpArtLab {
  OpArtLab._();

  static const _kFontFam = 'OpArtLab';
  static const _kFontPkg = null;

  static const IconData quarter_square = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quarter_triangle = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mini_circle = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData half_triangle = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData half_circle = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quarter_circle = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData recursion_depth = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData recursion_ratio = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shapes = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pointiness = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData L = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData horizontal_drift = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vertical_drift = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData O = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData horizontal_offset = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vertical_offset = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallpaper_ratio = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData line_horizontal = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData line_vertical = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData line_diagonal_right = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData line_diagonal_left = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bulge = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData s_shape = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);

}
